### PR TITLE
fix(riklet): microVM external network access

### LINKED ISSUE #115: regression: functions are unable to call external services
## What needs to be done ?

* Allow microVms networks to call external networks

## Why it needs to be done ?

* Latest release `1.1.0-rc1` changed the iptables behavior and created this bug

### PR DESCRIPTION
**Pull request by AlexandreBrg**
Closes #115 

## 📑 Description

- Remove deprecation of arguments `ifnet` and `ifnet_ip`
- Rename arguments `ifnet` and `ifnet_ip` to `iface` and `iface_ip`
- Add auto-detection of iface used to access external network, and the default gateway
- `ifnet` and `ifnet_ip` can supersed the auto-detection
- Creates few Iptables rules in order to allow forwarding of packets from microVM to external networks

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code is documented
- [x] I provided unitary tests or procedure to test my code
- [x] My PR have a clear description of what my code is supposed to do

### CODE REVIEW

File: riklet/src/cli/function_config.rs [hunk 1]
```diff
@@ -7,24 +9,34 @@ use clap::Parser;
...
         let opts = FnConfiguration::get_cli_args();
-        FnConfiguration::from(opts)
+
+        let gateway_ip = match opts.iface_ip {
+            Some(ip) => ip,
+            None => get_default_gateway()?,
+        };
+        let iface = match opts.iface {
+            Some(iface) => iface,
+            None => get_default_iface()?,
```
Comment (MaloPolese) [inline riklet/src/cli/function_config.rs:33]: 🟢 maybe anyhow to NetworkError ? 
hummm i don't know

**Review by MaloPolese — APPROVED** [review]

File: riklet/src/cli/mod.rs [hunk 2]
```diff
@@ -36,19 +36,15 @@ pub struct CliConfiguration {
...
     #[arg(
         long,
-        value_name = "IFNET_IP",
-        env = "IFNET_IP",
+        value_name = "IFACE_IP",
+        env = "IFACE_IP",
         value_parser = value_parser!(Ipv4Addr)
     )]
-    pub ifnet_ip: Option<Ipv4Addr>,
+    pub iface_ip: Option<Ipv4Addr>,
```
Comment (MaloPolese) [inline riklet/src/cli/mod.rs:49]: you can rebase main and update the doc

File: riklet/src/cli/function_config.rs [hunk 3]
```diff
@@ -7,24 +9,34 @@ use clap::Parser;
...
+    pub iface: String,
 }
 
 impl FnConfiguration {
     fn get_cli_args() -> CliConfiguration {
         CliConfiguration::parse()
     }
 
-    pub fn load() -> Self {
+    pub fn load() -> Result<FnConfiguration, anyhow::Error> {
```
[the remark this answers is not in the document]
Comment (AlexandreBrg) [reply riklet/src/cli/function_config.rs:24]: Yes, load of configuration is at early step, and we can't handle errors here, so we just lift up the error so that the binary crash with a proper error. Error handling is overengineering here.

File: riklet/src/cli/function_config.rs (hunk 1 above)
Comment (AlexandreBrg) [reply riklet/src/cli/function_config.rs:33]: NetworkError is not related to an error given by a third party library, and as stated before, load of configuration (and of iface / gateway) is done so early that we can't handle errors and have a different behavior, that's why anyhow is used.

In general, I don't think we should be using proper Error type when we can't handle them properly with various cases.

File: riklet/src/cli/mod.rs (hunk 2 above)
Comment (AlexandreBrg) [reply riklet/src/cli/mod.rs:41]: Done

**Review by MaloPolese — APPROVED** [review]

**Review by thomasgouveia — APPROVED** [review]
Just tested and it work great! LGTM 🚀
