### PR TITLE
fix: repair logs in riklet

### LINKED ISSUE #43: Fix: logging is broken
Last rebase from polyxia-org fork has broke logging in riklet. 
This issue will fix it.

### PR DESCRIPTION
**Pull request by mflagey**
closes #43

### CODE REVIEW

File: riklet/src/main.rs [hunk 1]
```diff
@@ -7,12 +7,17 @@ mod structs;
...
 
 #[tokio::main]
 async fn main() -> Result<(), Box<dyn std::error::Error>> {
     tracing_subscriber::fmt()
-        .with_env_filter(tracing_subscriber::EnvFilter::from_default_env())
+        .with_env_filter(
+            tracing_subscriber::EnvFilter::from_default_env()
+                .add_directive(LevelFilter::INFO.into()) // set a default level for all events
+                .add_directive("h2=OFF".parse().unwrap()), // disable all events from the `h2` crate
+        )
```
Comment (hugoamalric) [inline riklet/src/main.rs:20]: This should be configurable according to the verbosity level

**Review by hugoamalric — CHANGES_REQUESTED** [review]

**Review by MaloPolese — APPROVED** [review]

**Review by hugoamalric — APPROVED** [review]
